spring:
  application:
    name: manage-message
  cloud:
    nacos:
      discovery:
        ip: localhost
        port: 8848
        username: nacos
        password: nacos

dubbo:
  protocol:
    name: dubbo
    port: 12344

  registry:
    address: nacos://127.0.0.1:8848
  scan:
    base-packages: com.github.quick.spring.boot.manage.message.api